### ISSUE TITLE
当读取一个slave禁用(diabled)时，timeout后连线数不断上升。

### ISSUE THREAD

**Issue by ymmemo** [things-go/go-modbus#10]
你好，目前测试一种情境:
使用一个client同时读取slave1,2，当其中一个slave被禁用(diabled)后，
会因为读取不到而重新连线，但连线数不断上升。

...
p :=gomodbus.NewTCPClientProvider("127.0.0.1:1502")
for {
time.Sleep(1 * time.Second)
fmt.Println("p.IsConnected()", p.IsConnected()) // is true
client.ReadHoldingRegisters(1, 1, 1)
client.ReadHoldingRegisters(2, 1, 1) // i/o timeout
...
}

使用模拟器ModRSsim2可以观察到连线数不断新增，这边针对timeout的处理是否正常?

**Comment by thinkgos** [comment]
@ymmemo 我看了下代码这是bug, 抱歉. 代码库是两年前写的,这个timeout也需要重新处理一下.

**Comment by thinkgos** [comment]
最近我花时间先行修复下这个issue.

**Comment by ymmemo** [comment]
@thinkgos 了解，这个代码库真的很有帮助，再麻烦您，谢谢

**Comment by thinkgos** [comment]
相关已修复
